import "./globals.css";
import { Inter } from "next/font/google";
import Background from "./components/Background";
import Header from "./components/Header";
import Body from "./components/Body";
import Footer from "./components/Footer";
import Contact from "./components/Contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background>
          <Header />
          {children}
        </Background>
        <Footer />
      </body>
    </html>
  );
}
